import { request } from "./request"
export const GETALLUSERS = request + "user/"
export const GETUSERID = request + "user/"
export const POSTUSER = request + "user"
export const LOGINUSER = request + "login"